apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appdemo
  labels:
    name: appdemo
spec:
  rules:
  - host: cluster.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: appdemo
            port: 
              number: 80
