apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appcore
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: appcore-aplicacion-replacepath@kubernetescrd
  labels:
    name: appcore
spec:
  rules:
  - host: cluster.local
    http:
      paths:
      - pathType: Prefix
        path: "/appcore"
        backend:
          service:
            name: appcore
            port: 
              number: 80
