apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appdemo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/paganuzzi/argocd.git
    targetRevision: HEAD
    path: appdemo
  destination:
    server: https://kubernetes.default.svc
    namespace: appdemo