apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appdemo
  namespace: argocd
  annotations:

    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: my-channel1;my-channel2
spec:
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/paganuzzi/argocd.git
    targetRevision: HEAD
    path: appdemo
  destination:
    server: https://kubernetes.default.svc
    namespace: appdemo