apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appdemo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paganuzzi/argocd.git
    targetRevision: HEAD
    path: appdemo
  destination:
    server: https://kubernetes.default.svc
    namespace: appdemo